#A process process for scoring the effectiveness of clustering from tn93 Output.
#USAGE: Rscript tn93Graph.R tn93output.csv

library(igraph)
####- TO-DO: Use ML for optimization. see Caret or e107 packages -####

#__________________________________________________________________________________________________________________________#

#Estimates the growth of clusters based on information from all years before the latest year.
####- TO DO: Add MANY more predictor variables for this estimation and improve upon the current ones -####
estimateGrowth <- function(inG) {
  #@param inG: The input graph (usually a subgraph forward-censored by year). The latest year represents the Upcoming year. 
  #@return: An attribute for the clusters representing the predicted growth of each one.
  
  #Obtain the present graph (ie. the subgraph contain all cases before the the latest/"upcoming" year) and it's cluster info
  presV <- V(inG)[V(inG)$year<max(V(inG)$year)]
  presG <- induced_subgraph(inG, presV, impl = "auto")
  clu <- components(presG)
  
  #Obtain the size of current clusters after excluding all vertices from the current year. (ie. The clusters without their recent growth)
  ####- TO DO: Confirm this is a mathematically valid method when taking into account cluster merging -####
  oldClu <- clu$membership[attr(clu$membership, "names") %in% V(presG)[V(presG)$year<max(V(presG)$year)]$name]
  
  #Obtain the recent cluster growth for each cluster (ie. the difference between old cluster sizes and new ones)
  ####- TO DO: Potentially better style and speed with lapply?
  for (i in 1:clu$no) {
    presCsize <- clu$csize[[i]]
    oldCsize <- length(oldClu[unname(oldClu)==i])
    clu$growth[[i]] <- presCsize-oldCsize
  }
  
  return(clu$growth)
}

#Determines the growth of clusters based on the new addition of cases in the latest year (ie. The Upcoming year)
getGrowth <- function(inG) {
  #@param inG: The input graph (usually a subgraph forward-censored by year). The latest year represents the Upcoming year. 
  #@return: An attribute for the clusters representing the growth of each cluster
  
  newV <- V(inG)[V(inG)$year==max(V(inG)$year)]
  
  #Obtain the present graph (ie. the subgraph contain all cases before the the latest/"upcoming" year) and it's cluster info
  presG <- inG - newV
  clu <- components(presG)

  #Initialize cluster growth at 0 for each cluster
  clu$growth <- integer(clu$no)
  
  #Obtains the interface between vertices from the upcoming year and vertices from the present year.  
  bridgeE <- E(inG)[newV%--%V(inG)[-newV]]
  bridgeG <- inG - V(inG)[-ends(inG, bridgeE, names=F)]
  
  #Redifine the upcoming and present vertices as only those in the interface
  newV <- V(bridgeG)[V(bridgeG)$year==max(V(bridgeG)$year)]
  presV <- V(bridgeG)[V(bridgeG)$year<max(V(bridgeG)$year)]
  
  #Compare and obtain the growth of each cluster based on the placement of each new vertex
  #A vertex added to multiple clusters is considered to increase each cluster's size by a fraction
  if (length(newV)!=0){
    for (i in 1:length(newV)) {
      v <- newV[[i]]
      es <- E(bridgeG)[inc(v)]
      cluIndex <- unname(clu$membership[attr(clu$membership, "names") %in% ends(bridgeG, es, names = T)])
      vWeight <- 1/length(levels(factor(cluIndex))) 
      clu$growth[cluIndex] <- clu$growth[cluIndex]+vWeight 
    }
  }
  
  return(clu)
}

getGrowthSimp <- function(inG) {
  
  inG <- subgraph.edges(ing, E(inG), delete.vertices = T)
  
  clu <- components(inG)
  newV <- V(inG)[V(ing)$year == max(V(inG)$year)]$name
  
  oldClu <- clu$membership[attr(clu$membership, "names") !%in% newV]
  
}

#Obtains a filtered subgraph of the full graph.
subGraph <- function(inG, y, d) {
  #@param y: The year that represents the latest year. We forward censor everything past this.
  #@param d: The distance that represents the optimal cutoff distance for the whole graph
  #@return: The filtered graph (forward censored and cut by an optimal distance)
  
  #Removes vertices beyond a current year
  outV <- V(inG)[V(inG)$year>y]
  outG <- inG - outV
  
  #Removes edges with distances above a certain cutoff
  outE <- E(outG)[E(outG)$Distance>=d]
  outG <- outG - outE

  return(outG)
}



#__________________________________________________________________________________________________________________________#


#Warnings are currently generated by maximum informative distance being reached in the objective function. 
#This is handled by the functions that use objF
options(warn=-1)
args <- 
#Expecting the output from a tn93 run formatted to a csv file.
#Expecting patient information in the format ID_Date
args = commandArgs(trailingOnly = T)
input <- read.csv(args[1], stringsAsFactors = F)

#Creates a graph based on the inputted data frame. The tn93 Distances become edge4 attributes
g <- graph_from_data_frame(input, directed=FALSE, vertices=NULL)

#Adds the ID's and Sample collection years as different vertex attributes for each vertex
temp <- sapply(V(g)$name, function(x) strsplit(x, '_')[[1]])
V(g)$name <- temp[1,]
V(g)$year <- as.numeric(temp[2,])
years <- levels(factor(V(g)$year))

#Initialize a dataframe for the output of Accuracy by year
output <- data.frame(Year = as.integer(years), 
                     Accuracy = double(length(years)), 
                     Distance = double(length(years)), 
                     Time = double(length(years)))

##########################################################
y <- '2010'
res <- {}
for (x in seq(0.005, 0.020, 0.002)) {
  print(x)
  
  filtrG <- subGraph(g, y, x)
  clusters <- getGrowth(filtrG)
  prediction <- estimateGrowth(filtrG)

  
  # generate data frame at level of clusters
  df <- data.frame(estimate=prediction, actual=clusters$growth)
  
  # number of new cases per cluster is count outcome 
  fit <- glm(actual ~ prediction , data=df, family='poisson')
    
  result <- fit$null.deviance - fit$deviance

  res <- cbind(res, result)
}
##########################################################

#Obtain the optimum cutoff distance for that year
####- TO DO: Have this be based upon optDist function (glm-based estimate) and then erase the outdated function above -####
dist <- prettyGoodDist(g)

#Generate the Output data
for (y in years) {
  #If the case has no previous years to compare against
  if (length(V(g)[V(g)$year<y])==0) next
  
  startT <- proc.time() 
  
  #Filter the input graph to the loop year (y). The loop year will represent the "Upcoming" Year
  filtrG <- subGraph(g, y, dist)
  
  #Obtain the accuracy (ie. The actual - expected cluster growth)
  growthDiff <- estimateGrowth(filtrG) - abs(getGrowth(filtrG))
  acc <- mean(growthDiff)
  
  #Populate the output data with accuracy and ideal cutoff distance
  output$Accuracy[output$Year==y] <- acc
  output$Distance[output$Year==y] <- dist
  
  #Populate the output data with the speed of this iteration
  endT <- proc.time()
  output$Time[output$Year==y] <- (endT-startT)
}

#Test
print(proc.time())
cat("\n")
print(output)